### ISSUE TITLE
scssが上手くいきません。

### ISSUE THREAD

**Issue by fasfafal** [fasfafal/pf_app#103]
使い方
下記の項目の※部分を削除し各項目をすべて埋める形で記載してください

解決したいこと・達成したいものについて
scssで指定したtextの色を変更したいです。

聞きたいこと・アドバイスが欲しいこと
```.tab-container {
    display: flex; // フレックスボックスを使用して横並びに
    border-bottom: 2px solid #ccc; // 下にボーダーを追加
    justify-content: space-between; // 均等に配置
    margin: 20px 0; // 上下のマージンを調整
   
  
    .tab {
      flex:1 ; // 均等に広がるようにする
      text-align: center; // テキストを中央揃え
      padding: 50px 20px; // タブの内側の余白
      background-color: #007bff; //ボタンの背景色
      cursor: pointer; // カーソルをポインターに
      text-decoration: none; // リンクの下線を消す
      color: #b91e68; // テキストカラー
  
      &:hover {
        background-color: #f0f0f0; // ホバー時の背景色
      }
  
      &.active {
        font-weight: bold; // アクティブタブの太字
        border-bottom: 2px solid #007bff; // アクティブタブの下にボーダー
      }
    }
  }
```
において
color: #b91e68; // テキストカラー
がローカル環境で反映されずに困っています。
実装の際に参考にした資料等

[この記事です。](https://www.kagoya.jp/howto/itglossary/web/scsswriting/) 現状のコードの状態がわかるURLプルリクエスト・リポジトリ等

[このプルリクエストです。](https://github.com/fasfafal/pf_app/pull/102#issue-2588667835)

現状のコードの状態がわかるURLのどこが関係していると考えているのか
home/index.scssのtabが関係しています。

検証した結果から分かったこと・考えたこと
rails assets:clobber
rails assets:clean
rails assets:precompile
を行っても上手くいかないことがわかりました。

**Comment by kenchasonakai** [comment]
.tabのcolor以外のCSSは適応されていてcolorのみが反映されていない状態ということでしょうか？
また、cssが適応されていることがわかるようなスクリーンショット等を貼っていただけると状況がわかりやすいため対応お願いします

```
.tab {
  flex:1 ; // 均等に広がるようにする
  text-align: center; // テキストを中央揃え
  padding: 50px 20px; // タブの内側の余白
  background-color: #007bff; //ボタンの背景色
  cursor: pointer; // カーソルをポインターに
  text-decoration: none; // リンクの下線を消す
  color: #b91e68; // テキストカラー

  &:hover {
    background-color: #f0f0f0; // ホバー時の背景色
  }

  &.active {
    font-weight: bold; // アクティブタブの太字
    border-bottom: 2px solid #007bff; // アクティブタブの下にボーダー
  }
}
```

また、マークダウンが崩れていると思うのでマークダウンの書き方を再度調べてみてください

**Comment by fasfafal** [comment]
中井講師
返信ありがとうございます。

[![Image from Gyazo](https://i.gyazo.com/ffcaf3986f8c218f3d4261db4cb16fe0.gif)](https://gyazo.com/ffcaf3986f8c218f3d4261db4cb16fe0)

gif内の矢印の部分で表示されたテキスト部分が
反映されていません。

リンクの下線が消えない点もありました。

以上確認をお願いします。

**Comment by kenchasonakai** [comment]
ありがとうございます！
であればリンクの文字に対して`.tab`のクラスが当たっていないのが原因ではないかなと思います
下記のような形でaタグに対してスタイルが当たるようにしてみるとよいかもです

```
.tab {
  flex:1 ; // 均等に広がるようにする
  text-align: center; // テキストを中央揃え
  padding: 50px 20px; // タブの内側の余白
  background-color: #007bff; //ボタンの背景色
  cursor: pointer; // カーソルをポインターに

  a {
    color: #b91e68; // テキストカラー
    text-decoration: none; // リンクの下線を消す
  }

  &:hover {
    background-color: #f0f0f0; // ホバー時の背景色
  }

  &.active {
    font-weight: bold; // アクティブタブの太字
    border-bottom: 2px solid #007bff; // アクティブタブの下にボーダー
  }
}
```

**Comment by fasfafal** [comment]
中井講師
回答ありがとうございます。
ご指摘の通りに直した結果

下記の様に上手くいきました。
ありがとうございます。
[![Image from Gyazo](https://i.gyazo.com/b3a79377c184e1b27c2b6281cbe838f1.gif)](https://gyazo.com/b3a79377c184e1b27c2b6281cbe838f1)

僕のクラスとaタグとlink toメソッド、divタグの関係性についての
知識が低いことが分かりました。

人に説明できるレベルまで
調べてみます。

今後ともよろしくお願いします。
